### ISSUE TITLE
about posec3d

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#1107]
I don't know the difference between clip_len and num_clips in posec3d.

**Comment by kennymckormick** [comment]
`clip_len` means the number of frames in one clip (which is 48 in our released configs). `num_clips` means how many clips to sample from a video (which is 1 in training, 10 in testing (we ensemble predictions of 10 clips to get the final result)).

**Comment by bit-scientist** [comment]
@kennymckormick , if the action duration is longer than normal, is it ok to increase `clip_len` to say 96? Also,  while testing, the `num_clips` is also increased twice at max.

**Comment by bit-scientist** [comment]
> @kennymckormick , if the action duration is longer than normal, is it ok to increase `clip_len` to say 96? Also, while testing, the `num_clips` is also increased twice at max.

@kennymckormick may I have your attention please?

**Comment by kennymckormick** [comment]
I think 96 might be too large for a 3D-CNN backbone. Note that we use uniform sampling to sample frames, with 48 frames, we can cover a relatively long sequence densely. In experiments, we do not observe any severe performance drop on skeleton sequences as long as dozens of seconds.

**Comment by bit-scientist** [comment]
If, say according to [UniformSampleFrames](https://mmaction2.readthedocs.io/en/latest/api.html#mmaction.datasets.pipelines.UniformSampleFrames), I have a 20s long video with 30 fps (frame id in range [0, 599].), and the actual action starts at around 2s and ends at around 18s, which means action occurs for around 16 seconds. Which of the following would be a better choice?

1.  `clip_len = 60` and `num_clips = 1` 
Only 60 frames for training.
2. `clip_len = 60` and `num_clips = 2` 
In this case, does uniform sampling divide 20s video into 2 clips (since `num_clips = 2`) and extract 60 frames per clip (overall 120)? Ultimately, the model trains these 120 frames and label a particular class category, right?
3. `clip_len = 32` and `num_clips = 4`
Assuming the above is true, 128 frames (from 4*32) for training.

The speed is of no importance here, the task is to cover as many frames as possible because of the long action duration.
Thanks in advance!

**Comment by kennymckormick** [comment]
I think the num_clips should be set to 1 during training. Note that UniformSampleFrames works in this way:

Let's say we have 600 frames and set the clip_len to 60, then for every 10 frames, we randomly sample 1 frame: we choose 1 frame from [0, 10), 1 frame from [10, 20), etc. 

I think a good choice is to set clip_len to a relative large number, like 60 or 64 and set num_clips to 1 during training.
