### ISSUE TITLE
How to use optical arguments INPUT_STEP and STRIDE in Long video demo?

### ISSUE THREAD

**Issue by bhy0v587** [open-mmlab/mmaction2#1151]
Hi, I am new to mmaction2.

Recently I was using `demo/long_video_demo.py` to predict different labels using a single long video.
At first, I ran it with the default arguments and pre-trained TSM model based on Kinetics 400 dataset as follows and it updated the prediction every frame. It seems not good for analyzing a long video(1 minute) for every frame, e.g, the action of golf may take 2 or 3 seconds to act but analyzing every frame can not output the result like "golf driving".

`python demo/long_video_demo.py configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py checkpoints/tsm_r50_video_1x1x8_100e_kinetics400_rgb_20200702-a77f4328.pth video/golf.mp4 tools/data/kinetics/label_map_k400.txt output_video/result_golf.mp4 --label-color 0 255 0`

Then I looked through the optical arguments and `long_video_demo.py` and found that
1. Based on the configs of TSM, the `sample_length` was 8, which means with default arguments TSM only see 8 frames for each prediction.
2. Changing argument `INPUT_STEP` can get more spare input. It randomly selects 1 frame from every xx samples until filling up 8 frames. If I set `INPUT_STEP` to 20, it can see the 20x8 frames for each prediction.
3. `STRIDE` means the size of the sliding window, set 0 for sliding one frame every time and 1 for sliding all frame every time.

If my understanding is wrong, please let me know, thx!

Then I change my command as follows based on my understanding trying to analyze more frames.

`python demo/long_video_demo.py configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py checkpoints/tsm_r50_video_1x1x8_100e_kinetics400_rgb_20200702-a77f4328.pth video/golf.mp4 tools/data/kinetics/label_map_k400.txt output_video/result_golf.mp4 --input-step 20 --stride 0.5 --label-color 0 255 0`

This time it did output the prediction of "golf driving", however, if I change the `INPUT_STEP` to 40, 60, it output the same prediction as well.

My question is:
Is there a way to tell me how to set the best `INPUT_STEP` and `STRIDE` for a long video since the duration of each action may be different. Or just set it freely based on the duration of each action? 
I noticed that for training Kinetics 400 it inputs a 10-second video every time. Should I also set `INPUT_STEP` to adapt the 10-second length for each prediction? What is your strategy for setting `INPUT_STEP` and `STRIDE` for training and testing Kinetics 400 dataset?

I would be appreciated if there are any comments!

**Comment by dreamerlin** [comment]
1. It is hard to make a setting freely based on the duration of each action since we actually do not know how long each action happens.
2. For most 2D models, they usually take a sparse sampling strategy like [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py#L16). For 3D models, they usually take a sliding window sampling strategy like [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py#L21).

**Comment by bhy0v587** [comment]
@dreamerlin Thanks so much for your comments. 

I saw in the examples of Long video demo, you set `INPUT_STEP` to 3 for TSN and 1 for i3d.
I wonder how to set the `INPUT_STEP` for different models or we do not need to set `INPUT_STEP` usually.

I am also not sure about how to deal with the video with different duration of one action.
For example, I have a video including only one action, but the duration of this action is different (e.g., 3, 5, 7, 9, 15 seconds). 
Under this condition, how should I set the optical arguments or use other methods to precisely recognize all the actions in the video?
I would be appreciated if there are some suggestions.

**Comment by dreamerlin** [comment]
The aim of `INPUT_STEP` is originally to deal with the problem of hardware since some people can not process many times of inference. Without temporal localization, it is usually hard to make a setting freely based on the duration of each action since we actually do not know how long each action happens.

But if your videos are scene related, which the background contributes a lot (like `playing piano`, `playing basketball, `reading books`), A few frames, even only one frame, are also enough.

So the `INPUT_STEP` depends on the property of your dataset.
