### ISSUE TITLE
PoseC3D multiple persons with different actions in video

### ISSUE THREAD

**Issue by mayerg0** [open-mmlab/mmaction2#1319]
Let's say there is a video with two people, each one doing separate actions (no interactions), the naive approach would be to run action recognition model on each individual's keypoints separately. Is there any implementation that doesn't involve parallel inference?

**Comment by kennymckormick** [comment]
Currently, that's not implemented. But I think it's feasible to do so. In spatiotemporal action detection, we use a 3D-CNN backbone to extract features for a short clip and use RoIAlign to get the features of each individual. For skeleton-based settings, the input is heatmaps instead of RGB frames, while the pipeline remains the same.
