### ISSUE TITLE
running_mean should contain 51 elements not 75

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1438]
I'm training AGCN with the following command.

```
python tools/train.py configs/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d.py \
    --work-dir work_dirs/2sagcn_80e_ntu60_xsub_keypoint_3d \
    --validate --seed 0 --deterministic
```

Two pkl files from the following links are downloaded into the right folder.
```
 https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl
 https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl
```

When I run training command, I have error as 
`running_mean should contain 51 elements not 75`

Full errors are
```
2022-02-13 15:02:24,955 - mmaction - INFO - Checkpoints will be saved to /home/sysadmin/Nyan/mmaction2/work_dirs/2sagcn_80e_ntu60_xsub_keypoint_3d by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/apis/train.py", line 204, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 152, in train_step
    losses = self(skeletons, label, return_loss=True)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
    return self.forward_train(keypoint, label, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 15, in forward_train
    x = self.extract_feat(skeletons)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/skeleton_gcn/base.py", line 119, in extract_feat
    x = self.backbone(skeletons)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/Nyan/mmaction2/mmaction/models/backbones/agcn.py", line 329, in forward
    x = self.data_bn(x)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/sysadmin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 51 elements not 75

```

**Comment by gengenkai** [comment]
> es from the following links are downloaded into the right folder.

Hi, nyanmn. Please  refer to our script(tools/data/skeleton/gen_ntu_rgb_raw.py) to generate the skeleton data for gcn-based model( st-gcn, 2s-agcn). The data you use (https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl) is prepared for  posec3d model.

**Comment by nyanmn** [comment]
Thanks it works.

**Comment by edybk** [comment]
@gengenkai Can you please elaborate on the format needed to prepare a custom dataset as skeleton data for gcn-based model( st-gcn, 2s-agcn)?

**Comment by holopekochan** [comment]
> > es from the following links are downloaded into the right folder.
> 
> Hi, nyanmn. Please refer to our script(tools/data/skeleton/gen_ntu_rgb_raw.py) to generate the skeleton data for gcn-based model( st-gcn, 2s-agcn). The data you use (https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl) is prepared for posec3d model.
I got the same error when using https://download.openmmlab.com/mmaction/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d/2sagcn_80e_ntu60_xsub_keypoint_3d-3bed61ba.pth
with 

 configs/skeleton/2s-agcn/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py

I tested my skeleton data, it worked for stgcn and inference successfully. The error shows only in 2sagcn.

**Comment by YuktiADY** [comment]
> > > es from the following links are downloaded into the right folder.
> > 
> > 
> > Hi, nyanmn. Please refer to our script(tools/data/skeleton/gen_ntu_rgb_raw.py) to generate the skeleton data for gcn-based model( st-gcn, 2s-agcn). The data you use (https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl) is prepared for posec3d model.
> 
> I got the same error when using https://download.openmmlab.com/mmaction/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d/2sagcn_80e_ntu60_xsub_keypoint_3d-3bed61ba.pth with
> 
> configs/skeleton/2s-agcn/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py
> 
> I tested my skeleton data, it worked for stgcn and inference successfully. The error shows only in 2sagcn.


Hello,
 I converted my custom dataset to pkl file format according to [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl). For 3D action too the pickle file has to be in the same format as 2D? In case pickle file is different for 3D action recognition, where i can find the pickle file for 3D action because i tried to find but was unable to find the file.??

The config i used is this /mmaction2/configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint_3d.py

This is how my pickle file looks acc to ntu60_val like after conversion which i pass in the config

{'frame_dir': 'xxx',
'label': 2,
'img_shape': (1200, 1200),
'original_shape': (1200, 1200),
'total_frames': 60,
'keypoint': array([[[[-0.5752752 , 1.5449048 , -0.35333407],
[-0.45848957, 2.122168 , -0.7783565 ],
[-0.56915903, 2.5114708 , -0.58006483],
...,
[-1.0122216 , -0.09795046, 0.48847854],
[-0.14722271, 1.5622706 , -0.28381488],
[-0.14523879, 0.97209 , -0.12902533]],

      [[-0.9680816 ,  1.5107924 ,  0.16610162],
       [-0.4433155 ,  2.05 [-1.0122216 , -0.09795046,  0.48847854],
       [-0.14722271,  1.5622706 , -0.28381488],
       [-0.14523879,  0.97209   , -0.12902533]],

      [[-0.9680816 ,  1.5107924 ,  0.16610162],
       [-0.4433155 ,  2.0596356 , -0.62397057],
       [-0.677656  ,  2.3144732 , -0.35305595],
       ...,
       [-1.2954284 ,  0.23378837,  0.3796356 , -0.62397057],
       [-0.677656  ,  2.3144732 , -0.35305595],
       ...,
       [-1.2954284 ,  0.23378837,  0.37575948],
       [-0.2388921 ,  1.5274153 , -0.64014703],
       [-0.3291791 ,  0.66661656, -0.23001157]],

      [[-0.61705935,  1.555523  , -0.08190133],
       [-0.52065563,  2.1946764 , -0.34297913],
       [-0.5824748 ,  2.3736606 , -0.96034425],
       ...,
       [-0.93899643,  0.2939278 ,  0.3628401 ],
       [-0.19814743,  1.8153175 , -0.2928841 ],
       [-0.09000301,  0.8357382 , -0.19873522]],

      ...,

      [[-0.14083281,  1.5224657 , -0.4185819 ],
       [-0.6803411 ,  1.8933822 , -0.557123  ],
       [-0.606689  ,  2.0906188 , -0.49329972],
       ...,
       [-0.6312376 ,  0.25083363, -0.2258133 ],
       [ 0.12164785,  1.3438213 , -0.46219108],
       [-0.21164745,  0.6044779 , -0.26284647]],

      [[-0.06871447,  1.6594003 , -0.28470206],
       [-0.60743654,  1.9643098 , -0.7354354 ],
       [-0.3361878 ,  2.3228328 , -0.54341376],
       ...,
       [-0.8241794 ,  0.09567773, -0.13895753],
       [ 0.02210824,  1.4060467 , -0.50307167],
       [-0.02286317,  0.9342915 , -0.30795985]],

      [[-0.17271361,  1.6512171 , -0.6391277 ],
       [-0.7216524 ,  2.121202  , -0.6021455 ],
       [-0.43033436,  2.3559988 , -0.5735959 ],
       ...,
       [-0.9997901 , -0.14000493,  0.11607018],
       [-0.04694979,  1.5226002 , -0.34700772],
       [-0.24039742,  0.8633846 , -0.08101283]]]], dtype=float32),
'keypoint_score': array([[[1., 1., 1., ..., 1., 1., 1.],
[1., 1., 1., ..., 1., 1., 1.],
[1., 1., 1., ..., 1., 1., 1.],
...,
[1., 1., 1., ..., 1., 1., 1.],
[1., 1., 1., ..., 1., 1., 1.],
[1., 1., 1., ..., 1., 1., 1.]]], dtype=float16)},

Traceback :
Traceback (most recent call last):
File "/home/yukti/mmaction2/tools/train.py", line 222, in
main()
File "/home/yukti/mmaction2/tools/train.py", line 210, in main
train_model(
File "/home/yukti/mmaction2/mmaction/apis/train.py", line 232, in train_model
runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
self.run_iter(data_batch, train_mode=True, **kwargs)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
outputs = self.model.train_step(data_batch, self.optimizer,
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
return self.module.train_step(*inputs[0], **kwargs[0])
File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 155, in train_step
losses = self(skeletons, label, return_loss=True)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward
return self.forward_train(keypoint, label, **kwargs)
File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 16, in forward_train
x = self.extract_feat(skeletons)
File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 121, in extract_feat
x = self.backbone(skeletons)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/yukti/mmaction2/mmaction/models/backbones/stgcn.py", line 274, in forward
x = self.data_bn(x)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
return F.batch_norm(
File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/functional.py", line 2438, in batch_norm
return torch.batch_norm(
RuntimeError: running_mean should contain 68 elements not 75

Can you please help me how can i resolve this bug?

**Comment by SC-LAB-AI** [comment]
> > > > es from the following links are downloaded into the right folder.
> > > 
> > > 
> > > Hi, nyanmn. Please refer to our script(tools/data/skeleton/gen_ntu_rgb_raw.py) to generate the skeleton data for gcn-based model( st-gcn, 2s-agcn). The data you use (https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl) is prepared for posec3d model.
> > 
> > 
> > I got the same error when using https://download.openmmlab.com/mmaction/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d/2sagcn_80e_ntu60_xsub_keypoint_3d-3bed61ba.pth with
> > configs/skeleton/2s-agcn/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py
> > I tested my skeleton data, it worked for stgcn and inference successfully. The error shows only in 2sagcn.
> 
> Hello, I converted my custom dataset to pkl file format according to [ntu60_val](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl). For 3D action too the pickle file has to be in the same format as 2D? In case pickle file is different for 3D action recognition, where i can find the pickle file for 3D action because i tried to find but was unable to find the file.??
> 
> The config i used is this /mmaction2/configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint_3d.py
> 
> This is how my pickle file looks acc to ntu60_val like after conversion which i pass in the config
> 
> {'frame_dir': 'xxx', 'label': 2, 'img_shape': (1200, 1200), 'original_shape': (1200, 1200), 'total_frames': 60, 'keypoint': array([[[[-0.5752752 , 1.5449048 , -0.35333407], [-0.45848957, 2.122168 , -0.7783565 ], [-0.56915903, 2.5114708 , -0.58006483], ..., [-1.0122216 , -0.09795046, 0.48847854], [-0.14722271, 1.5622706 , -0.28381488], [-0.14523879, 0.97209 , -0.12902533]],
> 
> ```
>   [[-0.9680816 ,  1.5107924 ,  0.16610162],
>    [-0.4433155 ,  2.05 [-1.0122216 , -0.09795046,  0.48847854],
>    [-0.14722271,  1.5622706 , -0.28381488],
>    [-0.14523879,  0.97209   , -0.12902533]],
> 
>   [[-0.9680816 ,  1.5107924 ,  0.16610162],
>    [-0.4433155 ,  2.0596356 , -0.62397057],
>    [-0.677656  ,  2.3144732 , -0.35305595],
>    ...,
>    [-1.2954284 ,  0.23378837,  0.3796356 , -0.62397057],
>    [-0.677656  ,  2.3144732 , -0.35305595],
>    ...,
>    [-1.2954284 ,  0.23378837,  0.37575948],
>    [-0.2388921 ,  1.5274153 , -0.64014703],
>    [-0.3291791 ,  0.66661656, -0.23001157]],
> 
>   [[-0.61705935,  1.555523  , -0.08190133],
>    [-0.52065563,  2.1946764 , -0.34297913],
>    [-0.5824748 ,  2.3736606 , -0.96034425],
>    ...,
>    [-0.93899643,  0.2939278 ,  0.3628401 ],
>    [-0.19814743,  1.8153175 , -0.2928841 ],
>    [-0.09000301,  0.8357382 , -0.19873522]],
> 
>   ...,
> 
>   [[-0.14083281,  1.5224657 , -0.4185819 ],
>    [-0.6803411 ,  1.8933822 , -0.557123  ],
>    [-0.606689  ,  2.0906188 , -0.49329972],
>    ...,
>    [-0.6312376 ,  0.25083363, -0.2258133 ],
>    [ 0.12164785,  1.3438213 , -0.46219108],
>    [-0.21164745,  0.6044779 , -0.26284647]],
> 
>   [[-0.06871447,  1.6594003 , -0.28470206],
>    [-0.60743654,  1.9643098 , -0.7354354 ],
>    [-0.3361878 ,  2.3228328 , -0.54341376],
>    ...,
>    [-0.8241794 ,  0.09567773, -0.13895753],
>    [ 0.02210824,  1.4060467 , -0.50307167],
>    [-0.02286317,  0.9342915 , -0.30795985]],
> 
>   [[-0.17271361,  1.6512171 , -0.6391277 ],
>    [-0.7216524 ,  2.121202  , -0.6021455 ],
>    [-0.43033436,  2.3559988 , -0.5735959 ],
>    ...,
>    [-0.9997901 , -0.14000493,  0.11607018],
>    [-0.04694979,  1.5226002 , -0.34700772],
>    [-0.24039742,  0.8633846 , -0.08101283]]]], dtype=float32),
> ```
> 
> 'keypoint_score': array([[[1., 1., 1., ..., 1., 1., 1.], [1., 1., 1., ..., 1., 1., 1.], [1., 1., 1., ..., 1., 1., 1.], ..., [1., 1., 1., ..., 1., 1., 1.], [1., 1., 1., ..., 1., 1., 1.], [1., 1., 1., ..., 1., 1., 1.]]], dtype=float16)},
> 
> Traceback : Traceback (most recent call last): File "/home/yukti/mmaction2/tools/train.py", line 222, in main() File "/home/yukti/mmaction2/tools/train.py", line 210, in main train_model( File "/home/yukti/mmaction2/mmaction/apis/train.py", line 232, in train_model runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run epoch_runner(data_loaders[i], **kwargs) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train self.run_iter(data_batch, train_mode=True, **kwargs) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter outputs = self.model.train_step(data_batch, self.optimizer, File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step return self.module.train_step(*inputs[0], **kwargs[0]) File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 155, in train_step losses = self(skeletons, label, return_loss=True) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 106, in forward return self.forward_train(keypoint, label, **kwargs) File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/skeletongcn.py", line 16, in forward_train x = self.extract_feat(skeletons) File "/home/yukti/mmaction2/mmaction/models/skeleton_gcn/base.py", line 121, in extract_feat x = self.backbone(skeletons) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/yukti/mmaction2/mmaction/models/backbones/stgcn.py", line 274, in forward x = self.data_bn(x) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward return F.batch_norm( File "/home/yukti/miniconda3/envs/demo/lib/python3.10/site-packages/torch/nn/functional.py", line 2438, in batch_norm return torch.batch_norm( RuntimeError: running_mean should contain 68 elements not 75
> 
> Can you please help me how can i resolve this bug?

Hello, have you solved it？？？？

**Comment by SC-LAB-AI** [comment]
You can set the number of channels to 4 in backbone
