### ISSUE TITLE
about tsn reference acc

### ISSUE THREAD

**Issue by potatowarriors** [open-mmlab/mmaction2#1542]
The **tsn** sthv1 reference acc is different from the actual one.
Why did this difference occur?

**tsn** sthv1 reference top 1 acc : 17.5 (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/README.md)
**tsm** paper top 1 acc : 19.7

**Comment by kennymckormick** [comment]
Hi, potatowarriors,
We cannot figure out why two numbers are different, since TSM didn't release their TSN training scripts and ckpts. 
BTW, both TSN performance are **extremely low** on SthV1, indicating that adopting TSN on datasets like SthV1 is not a good idea (although it's quite straightforward).

**Comment by potatowarriors** [comment]
Oh, thank you so much!!
I will send an e-mail to the author of the paper to check
thank you so much for replying!!!
