### ISSUE TITLE
docs_zh_CN/demo.md 更新

### ISSUE THREAD

**Issue by Nothing1024** [open-mmlab/mmaction2#1570]
**发现时间：2022/4/9 16:40**

我发现官方中文文档中的**demo实例**中的参数**font-size**已经在[[Improvement] Make demo more robust in cross-platforms](https://github.com/open-mmlab/mmaction2/commit/a29e4aa9f9cd5e730b5a99dd5f74748676e32c30)中被**font-scale**替换。

目前英文文档已更新相关参数，但中文文档仍未更新。

且[英文Demo文档](https://mmaction2.readthedocs.io/en/latest/demo.html#)中右上角指向链接[Edit on GitHub](https://github.com/open-mmlab/mmaction2/blob/master/docs/demo.md)无效，查看[对应目录](https://github.com/open-mmlab/mmaction2/tree/master/docs)确实没有发现demo.md

在Edge+Chrome浏览器访问情况相同，且已经测试了开关代理，隐私模式

**Comment by kennymckormick** [comment]
@Dai-Wenxun . You can have a look on this issue.

**Comment by kennymckormick** [comment]
Hi, Nothing1024, 
The link failure is because that we generate docs/demo.md at build time, thus the [Edit on GitHub](https://github.com/open-mmlab/mmaction2/blob/master/docs/demo.md) link doesn't work. Currently, we can not fix this link failure. You can edit `demo/demo.md` to update the related doc.
For the first problem, it is fixed in #1587.
