### ISSUE TITLE
Confused arguments: 'to_bgr' and 'to_rgb'

### ISSUE THREAD

**Issue by yeliudev** [open-mmlab/mmaction2#1616]
mmaction2 uses the argument `to_bgr` when normalizing the images (see [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/augmentations.py#L1412)). Specifically, this argument is passed to `mmcv.imnormalize_`. However, this method only supports `to_rgb` but not `to_bgr`. Does it mean that all the models in mmaction2 are actually trained in BGR mode?

**Comment by dreamerlin** [comment]
We use rgb

https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L1303
https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L1233-L1234

And actually, `to_bgr` and `to_rgb` are the same in `mmcv.imnormalize_` since COLOR_BGR2RGB = 4 and cv2.COLOR_RGB2BGR = 4

**Comment by yeliudev** [comment]
I see. Thanks for your reply!
