### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by IDayday** [open-mmlab/mmaction2#164]
I want know whether test.py can output the predicted values( if I have 3cls, it can output 0 or 1 or 2? ) or labels? 
I followed your guide to add '-out result,json', but I can't understand what  the values mean in the result.json .

Also, I want to ask a question about the model:
As a 3D model, whether Slowfast can predict with only one picture as input? 
I have tried my idea, but it doesn't work, maybe I get wrong dataset for rawframes.

**Comment by dreamerlin** [comment]
1. The shape of the value in the `result.json` corresponds with the num of the classes and each element of an array indicates the score of the corresponding class. 
2. It is ok to take a picture as input by expanding the dimension of it into a acceptable shape for the network. But since a single picture contains no temporal information, I guess it may be not a good idea.
