### ISSUE TITLE
Explanation on SampleFrames,  clip_len=32, frame_interval=2, num_clips=10

### ISSUE THREAD

**Issue by alitirmizi23** [open-mmlab/mmaction2#1662]
**training parameters explanation required:**
Could you elaborate a bit more on **SampleFrames**,  **clip_len**=32, **frame_interval**=2, **num_clips**=10 in the train/test/val_pipleline and what this means when I use an I3D action recognizer for inference?
 
Using 10s videos takes ~40-60s for inference and shorter videos take much less (e.g ~6-10s). Does this have to do with clip_len and num_clips? Another thing I observed is, for higher resolution videos, the inference seems slower than for lower resolution videos (given same video lengths i.e 10s). 

From the paper of I3D: Training videos using random 64 frames sampled from videos whereas testing was done by averaging predictions over multiple 64-frame clips. Is that why training pipeline has different parameters than the testing pipeline? Also, i'm still confused as to whether clip_len = 32, frame_interval =2 and num_clips = 1 means only 1 clip will be used for training from a single video comprising of 10secs?

**Comment by alitirmizi23** [comment]
Just to clarify: the videos that are slow in inference are 1080 x 1920 (h x w) while the ones that are fast are ~ 240 x 420

**Comment by yyccli** [comment]
Hi, about explanations on SampleFrames, you may refer to this disscurrsion #655

**Comment by makecent** [comment]
I think "clip_len=32, frame_interval=2" should be easy to understand, it's just a **video clip** that consists of **32** frames of interval **2** (thereby covering a duration of 64-frame). The issue is **_where_** the clip is sampled from?

For training, it's **randomly** sampled along the temporal axis. So actually we are inputing a **local** content of a training video for classification, and this is a common recipe. Since we only use **one** clip for each pass, the num_clips equals **1**.

For the testing, we **evenly** sample **10** clips along the time axes, thereby num_clips=**10**. You may also noticed that there is always a `test_mode=True` in the `SampleFrames` of val/test. It actually means that the 10 clips are evenly (instead of randomly) sampled. BTW, the final score is obtained by averaging the scores of the ten clips.

**Comment by alitirmizi23** [comment]
Thanks for the responses.

**Comment by alitirmizi23** [comment]
I know I closed this, but just to confirm, when we have ThreeCrop in the test/val pipeline, we end up with 3x the clips compared to if we have CenterCrop for example.. how would the inference be done in such a pipeline?

**Comment by makecent** [comment]
> I know I closed this, but just to confirm, when we have ThreeCrop in the test/val pipeline, we end up with 3x the clips compared to if we have CenterCrop for example.. how would the inference be done in such a pipeline?

ThreeCrop perform test augmentation spatially. Along the longer image side, evenly sample three crops. The final score is averaged.
