### ISSUE TITLE
How many frames per second are used in SlowFast training. (annotation has 1 frame) but in rawframes folder we have 30 frames for 1 second

### ISSUE THREAD

**Issue by Mitesh512** [open-mmlab/mmaction2#1690]
Hi @lindahua / @usernameandme/ @yuta1125tp/ @jenhaoyang/ @hellock,   

According to the paper:
The Slow pathway uses a large temporal stride (i.e. number of frames skipped per second) τ, typically set at 16, allowing for approximately 2 sampled frames per second.
The Fast pathway uses a much smaller temporal stride τ/α, with α typically set at 8, allowing for 15 frames per second.

However,
In annotations, we have only 1 frame annotated for each second. and in the code also we just read the path of 1 annotated frame only.
So the question is where do we use all the 15 frames per second and 2 frames per second for a fast and slow path for training?
could you please explain how it works?

Thanks,
Mitesh

**Comment by hukkai** [comment]
For Kinetics training, one video clip has an annotation. I guess you might refer to AVA training. "1 frame annotated for each second" is not very precise since the annotation is for the 1 second video clip centered at each time stamp (we can think actions do not change in such a short time).

"in the code also we just read the path of 1 annotated frame only" As far as I know it is not true for mmaction2. It will read Txτ frames centered at the annotation time stamp.

**Comment by hukkai** [comment]
@Mitesh512 If you have any questions, feel free to re-open the issue. Thanks!
