### ISSUE TITLE
Why is data_batch['imgs'].shape[0] not euqual to batchsize?

### ISSUE THREAD

**Issue by hanchenchen** [open-mmlab/mmaction2#1734]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help. 
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I set videos_per_gpu = 8. But the dimension of data_batch is torch.Size([1, 1, 3, 32, 224, 224]). 
I want to do manifold mixup in a batch. How should I mixup features from different samples in a batch?

**Comment by hukkai** [comment]
@hanchenchen According to this Mixup implementation, the first dimension of the imp should equal batch size:
https://github.com/open-mmlab/mmaction2/blob/40643bce66e78fbe525c1922329e82480f2aae0b/mmaction/datasets/blending_utils.py#L60
Could I know which config you are using so that I can check the batch shape?

**Comment by hanchenchen** [comment]
I am using this config:　https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/configs/recognition/swin/swin_base_patch244_window877_kinetics400_1k.py

**Comment by hukkai** [comment]
I think the first dimension of imp should be the batch size according to this line:
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/db018fb8896251711791386bbd2127562fd8d6a6/configs/recognition/swin/swin_base_patch244_window877_kinetics400_1k.py#L24
 Will run this config tomorrow and check

**Comment by hukkai** [comment]
@hanchenchen The reason is this line:
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/db018fb8896251711791386bbd2127562fd8d6a6/configs/recognition/swin/swin_base_patch244_window877_kinetics400_1k.py#L117

By using`update_interval=8` the model will split the batch into 8 piece and do forward 8 times, and then do backward 1 time.

**Comment by hukkai** [comment]
@hanchenchen If you need further discussion, feel free to re-open this issue. Thanks!
