### ISSUE TITLE
Backbone ResNetAudio does not have conv 'ConvAudio' module

### ISSUE THREAD

**Issue by yyccli** [open-mmlab/mmaction2#1953]
I'm using mmAction2 do some audio recognition tasks. I want to reuse the [ResNetAudio](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/backbones/resnet_audio.py) backbone in my own project.

In this backbone we need to build a basic ConvModule named **ConvAudio**:

![image](https://user-images.githubusercontent.com/25741435/192192820-6f71ca05-02a0-4794-89e2-2199ac685614.png)

However i cannot find this module in mmcv.cnn:

![image](https://user-images.githubusercontent.com/25741435/192192912-5dda570d-e847-486d-bec1-038fd13f3a19.png)

which means i cannot build this backbone for now.

There is another issue talked about audio recognition #1533 and gives two config files. One use a *ResNetAudio* backbone and another use a plain *ResNet* backbone. Is there any difference between this to backbone? or do i just need to use the plain *ResNet* backbone to do this?

**Comment by Dai-Wenxun** [comment]
[ConvAudio](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/common/conv_audio.py#L9) is registered in mmaction2 instead of mmcv. Compared with Resnet, there are some special designs for ResnetAudio. Check ConvAudio module for more details. Practice brings true knowledge, good luck!

**Comment by yyccli** [comment]
Thanks for your response.
