### ISSUE TITLE
`AttributeError: VideoDataset: Imgaug: module 'imgaug.augmenters.pillike' has no attribute 'sometimes'

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmaction2#2012]
Hi, I tried to use 'Sometimes' parameter in config for Imgaug, but got error

`AttributeError: VideoDataset: Imgaug: module 'imgaug.augmenters.pillike' has no attribute 'sometimes'

my dict
````
dict(type='Imgaug', transforms=[
        dict(type='Sometimes', 
            children=[
                dict(type='Crop', percent=(0, 0.1)),
                dict(type='Affine', rotate=(-45, 45))
                ]
        )
    ]
    ),
```

How I should use "Sometimes" correctly?

**Comment by cir7** [comment]
Hi, @soltkreig ,  from the error message, i guess that you miswrite `Sometimes` as `sometimes`, but it's correct in your config，this confuse me. 
Actually, i use your config, get another error: `Imgaug: __init__() got an unexpected keyword argument 'children'`, this is due to class `Sometimes` doesn't have parameter `children`, but parameter `then_list`.
However, our `Imgaug` is actually a wrapper to imgaug library, and only support dynamic create `Augmenter` instance in `children`, and the meta aug `Sometimes` requires `then_list` is a list of `Augmenter` instances. 
you can refer to this [pr](https://github.com/open-mmlab/mmaction2/pull/2015/files) to modify your `Imgaug` code,
and a usable config as follows:

-     dict(type='Imgaug', transforms=[
        dict(type='Sometimes', 
            then_list=[
                dict(type='Crop', percent=(0, 0.1)),
                dict(type='Affine', rotate=(-45, 45))
                ])]),

**Comment by cir7** [comment]
@soltkreig  If you have any further questions, feel free to re-open the issue. Thanks!
