### ISSUE TITLE
channel mismatch error in stgcn

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmaction2#2060]
After I've trained the 'configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py' with the custom data, Use the command 'python demo\ demo_framework.py data\lameness\S001C001P001R004A001.mp4 data\lameness\out.mp4 --config configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py --checkpoint  work_dirs\stgcn_80e_ntu60_xsub_keypoint\epoch_80.pth --det-config demo\faster_rcnn_r50_fpn_2x_coco.py --det-checkpoint  checkpoints\epoch_35.pth --pose-config demo\hrnet_w32_coco_256x192.py --pose-checkpoint  This is a test that I found in a video I checkpoints\best_PCK_epoch_760.pth'.
![image](https://user-images.githubusercontent.com/115400289/202154826-870dc44d-d7f4-4214-8c81-145631e08879.png)

**Comment by cir7** [comment]
@hsp2454 The bug is still due to the mismatch of `num_node` in config and input data. From the reported error, I assume that you specify the `num_node` in stgcn as 21, however, pose estimation config output channel is 17, and the pose checkpoint mismatch with pose config, since there is a mismatch warning when load it.
please make sure that the pose estimation model and stgcn have same `num_node`, and the corresponding config is compatible

**Comment by xiaoxin-Crayon** [comment]
if i use a custom dataset to train stgcn, what files do I need to modify.
I just modify: 
1. stgcn_80e_ntu60_xsub_keypoint.py in configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint_3d.py
2. graph.py in mmaction/models/skeleton_gcn/utils/graph.py
is that enough?

**Comment by cir7** [comment]
@xiaoxin-Crayon I think you are right
