### ISSUE TITLE
incorporating a test dataset into testerboradHook

### ISSUE THREAD

**Issue by dralmadani** [open-mmlab/mmaction2#2175]
I try to analyze the epochs and iterations of the data.
So I add the teserboradHook and modify the workflow in the configuration file as follows: `workflow = [('train', 1)]` --- to be --> `  workflow = [('train', 1), ('val', 1)]`
according to :
[Customize Workflow](https://mmaction2.readthedocs.io/en/latest/tutorials/7_customize_runtime.html?highlight=workflow%20%3D%20%5B(%27train%27%2C%201)%2C%20(%27val%27%2C%201)%5D#customize-workflow)

My question is:
When I create a workflow with the test dataset, I do as follows:   `workflow = ('train', 1), ('val', 1), ('test', 1)] `  for checking without learning  
I get an error because there is **no function test function for workflow** , So, I try to update [mmcv/runner/epoch_based_runner.py](https://mmcv.readthedocs.io/en/latest/_modules/mmcv/runner/epoch_based_runner.html)

**Comment by Dai-Wenxun** [comment]
I can't figure out why you need `('test', 1)`. Is there any difference between the validation dataset and the test dataset?

**Comment by dralmadani** [comment]
If you talk about the Val function it's great but if use 3rd dataset that rase another problem when pop a  model.pth for validation then pop the same model.pth for the test 


`# Build the dataset
datasets = [build_dataset(cfg.data.train), build_dataset(cfg.data.val) , build_dataset(cfg.data.test)]`

`cfg.workflow = [('train',1)
, ('Val',1)
, ('Val',1)]`



about the data : yes there are different

**Comment by Dai-Wenxun** [comment]
So, you mean multi-dataset validation when training, right?

**Comment by dralmadani** [comment]
> So, you mean multi-dataset validation when training, right?

You can say that but I don't want to use the 3rd dataset on training a model only using it for the tenserboard chart through tenserboardHook

**Comment by Dai-Wenxun** [comment]
Under the current framework, it is tricky to tackle this problem.

**Comment by Dai-Wenxun** [comment]
How about merging two validation datasets into one validation dataset? You can modify the [code](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L139-L243) for evaluation to solve this problem. If you do so, you must keep the order of the annotations (e.g., the preceding annotations all belong to the first dataset, and the latter belong to the second) so that the evaluation function can take the preceding results (`first_results = results[:len(first_dataset)]`) to calculate the metrics of the first dataset, as well as the second dataset.
