### ISSUE TITLE
Question about FineGYM dataset's Ground-Truth bounding boxes

### ISSUE THREAD

**Issue by Haoran-Qi** [open-mmlab/mmaction2#2179]
According to https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton,

In the introduction section about generating 2D skeleton for FineGYM,

_"For FineGYM, we use Ground-Truth bounding boxes for the athlete instead of detection bounding boxes."_

I didn't see available Ground-Truth bounding boxes mentioned in the FineGYM paper nor official website, 
wondering if anyone know what that referring to!

Thanks ahead

**Comment by Haoran-Qi** [comment]
anyone has some ideas?

**Comment by cir7** [comment]
Hi, @kennymckormick, could you please give some suggestions

**Comment by Haoran-Qi** [comment]
Can someone gives me a hint?

**Comment by kennymckormick** [comment]
The GT bbox annotations of FineGYM is now available at https://download.openmmlab.com/mmaction/pyskl/data/gym/gym_gt_bboxes.pkl. For more information, you can refer to this page: https://github.com/kennymckormick/pyskl/blob/main/tools/data/README.md.

**Comment by Tristan-J** [comment]
@kennymckormick  thanks for your effort to skeleton-based action understanding!
For the FineGym bounding boxes, do you collect by manually labeling? Because for sports actions, obviously, it is hard to detect the fast moving body components and it is a HUGE work to extract from each frame. 
Thank you!
