### ISSUE TITLE
Train 2s-agcn with GYM [2D Skeleton] data

### ISSUE THREAD

**Issue by a-github-learner** [open-mmlab/mmaction2#2263]
First, thank you for your convenient and effective repo proposed on GitHub.

I try to train 2s-agcn network with GYM 2d skeleton. However, I find there don't exist any configs referring to such an attempt. So I would like to ask how to modify the config of [2sagcn_80e_ntu60_xsub_keypoint_3d.py](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/2s-agcn/2sagcn_80e_ntu60_xsub_keypoint_3d.py) to suit my demand? 

Thanks so much and looking forward to your early reply!

**Comment by Dai-Wenxun** [comment]
For skeleton-based action recognition, I recommend you use `1.x branch` instead of `master branch`. Here is the [Get_Started ](https://mmaction2.readthedocs.io/en/1.x/get_started.html#) tutorial of our new MMAction 1.x version. 

After 1.x is Installed, you can refer to this [config](https://github.com/open-mmlab/mmaction2/blob/1.x/configs/skeleton/2s-agcn/2s-agcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py) of 2s-agcn for ntu60_2d skeleton data. The 2d skeleton data for GYM can be downloaded from this page. https://github.com/open-mmlab/mmaction2/tree/dev-1.x/tools/data/skeleton.

Usually, you just need to modify these two lines to change the number of the classes (i.e., 60 -> 99) and the path to your data.

https://github.com/open-mmlab/mmaction2/blob/1.x/configs/skeleton/2s-agcn/2s-agcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py#L12
https://github.com/open-mmlab/mmaction2/blob/1.x/configs/skeleton/2s-agcn/2s-agcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py#L9

Good luck! Keep in touch! bro!
