### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by edanherrera** [open-mmlab/mmaction2#2337]
Hi. I am trying to train a model but it gives me the error "CUDA out of Memory".
![cuda](https://user-images.githubusercontent.com/91446757/229892783-cfec7afa-8c74-460e-a45f-d0e1412db117.png)

**Comment by Dai-Wenxun** [comment]
Hi there! "CUDA out of Memory" error is a common issue when training deep learning models, especially if the model or the batch size is large.

This error occurs when the GPU does not have enough memory to store all the tensors required for the current operation. There are a few things you can try to resolve this issue:

Reduce batch size: One of the most common ways to address this issue is to reduce the batch size. This reduces the amount of memory required to store the tensors in the GPU memory. You can try reducing the batch size and see if the error goes away.

Use smaller model: If reducing the batch size does not work, you can try using a smaller model with fewer layers or fewer neurons per layer. This will reduce the number of parameters that need to be stored in the GPU memory.

Use mixed precision training: Another way to reduce memory usage is to use mixed precision training. In mixed precision training, the model parameters are stored in half-precision (FP16) format instead of single-precision (FP32) format. This reduces the memory usage by half, but may also require changes to the training algorithm.

Use gradient accumulation: If reducing the batch size or using a smaller model is not an option, you can try using gradient accumulation. In gradient accumulation, the gradients are accumulated over multiple batches before updating the model parameters. This reduces the memory usage per batch, but may also increase the training time.

Use a GPU with more memory: If none of the above solutions work, you can try using a GPU with more memory. This may require changing your hardware or using a cloud-based GPU service.

I hope this helps!

**Comment by edanherrera** [comment]
it's works, thanks!

**Comment by T-wow** [comment]
Hello, how to specify gpu when doing training in mmaction2 version 1.2. thanks.
