### ISSUE TITLE
Mvit code error[Bug] 

### ISSUE THREAD

**Issue by commandermsv** [open-mmlab/mmaction2#2446]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

While training mvit-base-p244_32x3x1_kinetics400-rgb.py, I'm continuously getting this below msg,

/mmaction2/mmaction/models/utils/blending_utils.py:151: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').

### Describe the bug

While training mvit-base-p244_32x3x1_kinetics400-rgb.py, I'm continuously getting this below msg,

/mmaction2/mmaction/models/utils/blending_utils.py:151: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').

How to solve this?

**Comment by Dai-Wenxun** [comment]
This warning message is indicating that the usage of `floordiv` function in the code is deprecated in PyTorch, and that it will have a different behavior in a future version of PyTorch. Currently, floordiv function rounds towards zero, which can cause incorrect rounding for negative values.

Use `torch.div(a, b, rounding_mode='trunc')` instead of floordiv, which will provide the same behavior as floordiv in the current version of PyTorch.

We fix this warning in https://github.com/open-mmlab/mmaction2/pull/2449.
