### ISSUE TITLE
how to train on uniformer not uniformerv2

### ISSUE THREAD

**Issue by sumonky** [open-mmlab/mmaction2#2510]
### What is the problem this feature will solve?

no

### What is the feature?

no

### What alternatives have you considered?

how to train on uniformer not uniformerv2, there is no train pipeline in configs/recognition/uniformer/uniformer-base_imagenet1k-pre_16x4x1_kinetics400-rgb.py

**Comment by cir7** [comment]
Currently, we don't support training UniFormer due to the lack of computing resources, you could refer to the paper for training details. Looks like the training recipe is similar to [MViT](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/mvit/mvit-small-p244_32xb16-16x4x1-200e_kinetics400-rgb.py), which has been supported in MMAction2.
