### ISSUE TITLE
Prediction order across different machines

### ISSUE THREAD

**Issue by jinwchoi** [open-mmlab/mmaction2#283]
Hi,

When generating results.pkl In tools/test.py, the prediction order is kept the same across the different machines and the different number of gpus? In other words, the prediction order of the generated results.pkl, and the order of gt_labels generated in the mmaction/datasets/rawframe_datasets.py are the same?

I want to compare the results.pkl files generated by the different machines. But it seems that the orders are different. Can somebody tell me how to use the cached results.pkl file for evaluation and comparison? Thanks!

**Comment by dreamerlin** [comment]
Hi, the prediction order of the generated results.pkl, and the order of gt_labels generated in the `mmaction/datasets/rawframe_datasets.py` are the same, so that the [evaluate](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L171-L255) can be performed correctly. For more details, you can refer to [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/test.py)

**Comment by jinwchoi** [comment]
Oh I found the reason, `tools/data/ucf101/generate_rawframes_filelist.sh` shuffles validation data without a random seed. So it generates differently ordered validation listfiles across the different machines! Can you make it to use a random seed? Other people may encounter this issue later...

**Comment by dreamerlin** [comment]
Sorry for my late reply due to other projects. Here is the [fix](https://github.com/open-mmlab/mmaction2/pull/323) for your report
