### ISSUE TITLE
Request for feature of customing sampler

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#297]
**Describe the feature**
Sampler is a common feature of dataloader.
For the current version of mmaction, it sets [sampler=None](https://github.com/open-mmlab/mmaction2/blob/03e89da05bbff080a47cbe93599cbffe11f0de5e/mmaction/datasets/builder.py#L88) and [sampler=DistributedSampler](https://github.com/open-mmlab/mmaction2/blob/03e89da05bbff080a47cbe93599cbffe11f0de5e/mmaction/datasets/builder.py#L82). That makes mmaction not supporting customing sampling weighs for different samples, especially for dist_train.

**Motivation**
Customing sampler for dataloader is an important method for handling _imbalanced datasets_. 

**Related resources**
There are already some useful [samplers in PyTorch](https://pytorch.org/docs/stable/data.html?highlight=sampler#torch.utils.data.Sampler). e.g. torch.utils.data.WeightedRandomSampler.

**Comment by SuX97** [comment]
This [short cycle sampler](https://github.com/open-mmlab/mmaction2/blob/48330f28398a76f76b3d9e9f4d8965c281552855/mmaction/datasets/samplers/short_cycle_sampler.py) can be a reference.

**Comment by innerlee** [comment]
my understanding is that, we need to add an interface to allow customization, rather than providing concreate implementations?

**Comment by SuX97** [comment]
> my understanding is that, we need to add an interface to allow customization, rather than providing concreate implementations?

Right. Just an instruction on how to customize a sampler(or use that of Pytorch) and use it in mmaction2.

**Comment by MakeCent** [comment]
> my understanding is that, we need to add an interface to allow customization, rather than providing concreate implementations?

That's what I need. Actually, for me, I just want to use the existing sampler torch.utils.data.WeightedRandomSampler rather than custom a new one. 

While it seems that I have to change the build_dataloader func in builder.py to use another sampler. And even worse, I have to give up DistributedSampler. (to use DistributedSampler with custom sampler together, somebody has already raised similar question [somewhere](https://github.com/pytorch/pytorch/issues/23430))

**Comment by kennymckormick** [comment]
> > my understanding is that, we need to add an interface to allow customization, rather than providing concreate implementations?
> 
> That's what I need. Actually, for me, I just want to use the existing sampler torch.utils.data.WeightedRandomSampler rather than custom a new one.
> 
> While it seems that I have to change the build_dataloader func in builder.py to use another sampler. And even worse, I have to give up DistributedSampler. (to use DistributedSampler with custom sampler together, somebody has already raised similar question [somewhere](https://github.com/pytorch/pytorch/issues/23430))

I think it would be better to treat it case by case, rather than use an all-in-one wrapper to convert a sampler to DistributedSampler, because:
1. Pytorch itself doesn't provide lots of samplers (seems only 'WeightedRandomSampler' and 'SubsetRandomSampler' will be used), writing distributed versions of them may not take lots of time
2. How to convert Sampler to DistributedSampler is not-trivial, although it may have a trivial solution. Take `WeightedRandomSampler` as an example, when it runs in the distributed setting, the sampler of one process can either sample from the whole dataset with the given probability, or be responsible for part of the dataset. Different implementations may lead to different efficiency and model performance.

So I recommend you to implement a distributed version of your sampler. It may not take lots of time. Once you have implemented it, you can place it in the [distributed_sampler.py](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/samplers/distributed_sampler.py). The [DistributedPowerSampler](https://github.com/open-mmlab/mmaction2/blob/07dd1a918770902448fdcea17e1336649aced4cb/mmaction/datasets/samplers/distributed_sampler.py#L36) can be a reference example, which set a sampling probability for each class proportional to the power of #samples in that class.

**Comment by MakeCent** [comment]
> > > my understanding is that, we need to add an interface to allow customization, rather than providing concreate implementations?
> > 
> > 
> > That's what I need. Actually, for me, I just want to use the existing sampler torch.utils.data.WeightedRandomSampler rather than custom a new one.
> > While it seems that I have to change the build_dataloader func in builder.py to use another sampler. And even worse, I have to give up DistributedSampler. (to use DistributedSampler with custom sampler together, somebody has already raised similar question [somewhere](https://github.com/pytorch/pytorch/issues/23430))
> 
> I think it would be better to treat it case by case, rather than use an all-in-one wrapper to convert a sampler to DistributedSampler, because:
> 
> 1. Pytorch itself doesn't provide lots of samplers (seems only 'WeightedRandomSampler' and 'SubsetRandomSampler' will be used), writing distributed versions of them may not take lots of time
> 2. How to convert Sampler to DistributedSampler is not-trivial, although it may have a trivial solution. Take `WeightedRandomSampler` as an example, when it runs in the distributed setting, the sampler of one process can either sample from the whole dataset with the given probability, or be responsible for part of the dataset. Different implementations may lead to different efficiency and model performance.
> 
> So I recommend you to implement a distributed version of your sampler. It may not take lots of time. Once you have implemented it, you can place it in the [distributed_sampler.py](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/samplers/distributed_sampler.py). The [DistributedPowerSampler](https://github.com/open-mmlab/mmaction2/blob/07dd1a918770902448fdcea17e1336649aced4cb/mmaction/datasets/samplers/distributed_sampler.py#L36) can be a reference example, which set a sampling probability for each class proportional to the power of #samples in that class.

I will have a try. Thanks!

**Comment by MakeCent** [comment]
@kennymckormick I will have a try. Thanks!

**Comment by irvingzhang0512** [comment]
Actually, there are lots of similar solutions for this issue.

+ [PyTorch issue](https://github.com/pytorch/pytorch/issues/23430)
+ [DistributedSamplerWrapper and a few samplers implemented by catalyst](https://github.com/catalyst-team/catalyst/blob/master/catalyst/data/sampler.py)
