### ISSUE TITLE
tpn_tsm config file bug

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#328]
I'm working on GradCAM unittest right now. And I have trouble running tpn-tsm forward with `demo.py` & [this config file](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tpn/tpn_tsm_r50_1x1x8_150e_sthv1_rgb.py)

After some debugging, I think [test pipeline for tpn_tsm](https://github.com/open-mmlab/mmaction2/blob/7053406d571018437bbc07542f09a945e627ab6f/configs/recognition/tpn/tpn_tsm_r50_1x1x8_150e_sthv1_rgb.py#L72) is not working properly.

1. `FormatShape` is missing required positional argument `input_format`.
2. even when setting `input_format` to `NCHW`,  `size mismatch error`  occurs. 
    + input shape `(1, 8, 3, 224, 224)` like in the unittest is fine
    + num_clips=16, then input shape is `[1, 16, 3, 224, 224]`, raises size mismatch error.
    + add threecrop, then input shape is `[1, 24, 3, 224, 224]` , raises size mismatch error.
    + num_clips=16 & ad threecrop (like in the above config file test pipeline), input shape is `[1, 48, 3, 224, 224]`, raises size mismatch error.

**Comment by dreamerlin** [comment]
This config is referred from [original config](https://github.com/decisionforce/TPN/blob/master/config_files/sthv1/tsm_tpn.py). The `FormatShape` is right according to the original config since the backbone is `TSM`. And we didn't conduct exp for `num_clip=16`, same with the original repo. BTW, the performance for the original repo seems abnormal, so we didn't released ckpt for `sthv` in TPN
