### ISSUE TITLE
'Conv2plus1d' object has no attribute 'weight'

### ISSUE THREAD

**Issue by PoroWang** [open-mmlab/mmaction2#380]
Hi, I'm trying to use pretrained2d on r2plus1d ( loading the pretrained weight on 'torchvision://resnet50' then inflate).
However i got the error message " AttributeError: 'Conv2plus1d' object has no attribute 'weight' ".
I think it was caused by there's no weight def like Conv3d in Conv2plus1d.
Sorry for my poor English, and thanks for the awesome repo.

**Comment by SuX97** [comment]
R(2+1)D does not support inflating from 2d pretrained ckpts. Maybe we should assert that `pretrained2d` to be `false`.

**Comment by SuX97** [comment]
Umm, I believe you have not set `pretrained2d` to True, since it will throw AssertionError [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/backbones/resnet2plus1d.py#L15).

If you really want to inflate(which is not in the original paper and we don't know the result), my suggestion is that you can change [the conv_s here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/common/conv2plus1d.py#L66) into 'conv'. And I believe it will work the same way as I3D.

**Comment by PoroWang** [comment]
Of course i have modified the assert to True, otherwise this error will not occur.
Since i use the model i proposed which is similar to r2+1d, i have tried to use pretrainedR(2+1)D weight but it didn't reach the ideal performance.
Thus i hope to use 2D pretrained instead. I will keep trying. Thanks!
