### ISSUE TITLE
BMN reimplement differences

### ISSUE THREAD

**Issue by CarolineCheng233** [open-mmlab/mmaction2#532]
There are several different reimplements in this codebase from the original bmn paper.

**Describe the bug**
1. No group convolution but normal convolution in x_1d_b, x_1d_s and x_1d_e.
2. In Base Module, the second conv1d output feature dim is half of the first one but not the same. And so the input feature dim in Temporal Evaluation Module and Proposal Evaluation Module is half of the first conv1d output feature dim in Base Module.
3. In Temporal Evaluation Module, x_1d_s and x_1d_e in mmaction2 should share the same conv1d_3 kernel and get the first and second dim of the same output. Namely, Temporal Evaluation Module output 2\*T probability sequence using only one Conv1d but not two 1\*T output Conv1ds.
4. There are no conv1d kernels in Proposal Evaluation Module.
5. Only three conv2ds in Proposal Evalution Module but not four.
6. Corresponding modification in _forward function.

Appendix: BMN module figure
![image](https://user-images.githubusercontent.com/25295166/104148751-7ee2cc00-540e-11eb-9752-43f71bb70504.png)

**Bug fix**

After modified, AR@100 and AUC are more close to original paper.
![image](https://user-images.githubusercontent.com/25295166/104149757-6b396480-5412-11eb-82bd-5b7b3c7f65d1.png)

**Comment by SuX97** [comment]
> There are no conv1d kernels in Proposal Evaluation Module.

@CarolineCheng233 , thanks!

$conv3d_1$ has a kernel of 32, 1, 1, so it's equivalent to conv1d with kernel size 32.

**Comment by dreamerlin** [comment]
@CarolineCheng233 Would you help to provide a PR for the original BMN implementation without Backward compatibility breaking, since you have provided the result. That would be great! : P

**Comment by kimsimple** [comment]
Does anybody know why there is such a big gap between BMN(paper) and BMN(mmaction2) on Anet_v1.3?

Method | 0.5 | 0.75 | 0.95 | Average | Average
-- | -- | -- | -- | -- | --
BMN paper | 50.07 | 34.78 | 8.29 | 33.85 | 36.42
BMN mmaction2 | 42.25 | 31.04 | 9.58 | 30.04 | -
gap | 7.82 | 3.74 | -1.29 | 3.81 | -

**Comment by PeiqinZhuang** [comment]
> Does anybody know why there is such a big gap between BMN(paper) and BMN(mmaction2) on Anet_v1.3?
> 
> Method	0.5	0.75	0.95	Average	Average
> BMN paper	50.07	34.78	8.29	33.85	36.42
> BMN mmaction2	42.25	31.04	9.58	30.04	-
> gap	7.82	3.74	-1.29	3.81	-

I am also curious about the performance gap under the evaluation of mAP. Have you figured out what the cause is?

**Comment by SuX97** [comment]
Hi @kimsimple @PeiqinZhuang :
Thanks for asking! We have no idea how the original paper gets the reported mAP, but we have tried using the only other open repo of BMN for testing (see the last row) using the same proposal classification method of assigning the label from cuhk_mean_100. It turns out using their proposals and our label assigning/evaluation method, our mAP is slightly higher.

|config |feature | gpus | AR@100| AUC | AP@0.5 | AP@0.75 | AP@0.95 | mAP | gpu_mem(M) | iter time(s) | ckpt | log| json|
|:-:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:-:|---|:-:|:-:|---|
|[bmn_400x100_9e_2x8_activitynet_feature](/configs/localization/bmn/bmn_400x100_2x8_9e_activitynet_feature.py) |cuhk_mean_100 |2|75.28|67.22|42.47|31.31|9.92|30.34|5420|3.27|[ckpt](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_9e_activitynet_feature/bmn_400x100_9e_activitynet_feature_20200619-42a3b111.pth)| [log](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_9e_activitynet_feature/bmn_400x100_9e_activitynet_feature.log)| [json](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_9e_activitynet_feature/bmn_400x100_9e_activitynet_feature.log.json)|
| |mmaction_video |2|75.43|67.22|42.62|31.56|10.86|30.77|5420|3.27|[ckpt](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_video/bmn_400x100_2x8_9e_mmaction_video_20200809-c9fd14d2.pth)| [log](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_video/bmn_400x100_2x8_9e_mmaction_video_20200809.log) | [json](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_video/bmn_400x100_2x8_9e_mmaction_video_20200809.json) |
| |mmaction_clip |2|75.35|67.38|43.08|32.19|10.73|31.15|5420|3.27|[ckpt](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_clip/bmn_400x100_2x8_9e_mmaction_clip_20200809-10d803ce.pth)| [log](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_clip/bmn_400x100_2x8_9e_mmaction_clip_20200809.log) | [json](https://download.openmmlab.com/mmaction/localization/bmn/bmn_400x100_2x8_9e_mmaction_clip/bmn_400x100_2x8_9e_mmaction_clip_20200809.json) |
| [BMN-official](https://github.com/JJBOY/BMN-Boundary-Matching-Network) (for reference)* |cuhk_mean_100 |-|75.27|67.49|42.22|30.98|9.22|30.00|-|-|-| - | - |
