### ISSUE TITLE
How to use bi-direction on online video?

### ISSUE THREAD

**Issue by ZJU-lishuang** [open-mmlab/mmaction2#611]
In tsm paper, using bi-direction on offline video and using uni-direction on online video.
In this project,the tsm only has bi-direction module.

**Comment by innerlee** [comment]
Simply prepare enough frames for the model and do inference?

Could you give more details on the problem?

**Comment by ZJU-lishuang** [comment]
assume the online video frame is  [0,1,2,...,100,101,102,...].
Every 8 frame is put into the network,such as [0,8,8*2,...,8*8],and output the video recognition result.
Should I put [8,8*2,...,8*8,8*9] into the network next time?

**Comment by ZJU-lishuang** [comment]
> assume the online video frame is [0,1,2,...,100,101,102,...].
> Every 8 frame is put into the network,such as [0,8,8_2,...,8_8],and output the video recognition result.
> Should I put [8,8_2,...,8_8,8*9] into the network next time?

**Comment by innerlee** [comment]
If the stride is 8, then you can put `[n, n-8, n-16, ..., n-56]` to to network. Here n is the latest frame number you have

**Comment by ZJU-lishuang** [comment]
非常感谢您的帮助，提前祝您春节快乐
CURIOSITY

**Comment by irvingzhang0512** [comment]
For online applications, I wouldn't recommend to inference every n frames(synchronous mode, single-thread) due to limitted resources. [webcam_demo.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/webcam_demo.py) may be a better solution(multi-thread). 

Besides, keeping the last m frames(say 36 frames) in cache and inferencing with n selected frames from the cache may be useful.
