### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmaction2#715]
When we utilize train.py and tsm_r50_1*1*8_50e_sthv1_rgb.py,did it process data with image flip?I have experimented with classes like climb forward and run,the results show that they are alike.

**Comment by mytk2012** [comment]
I have checked code,it refers to crop not flip,but why does it occur?Maybe my label format is wrong.

**Comment by congee524** [comment]
Because there are some directional actions in sthv1&v2 such as `push left to right`.


But you can also use label mapping to apply flip on sthv1, referring to [tsm_r50_flip_1x1x8_50e_sthv1_rgb](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_flip_1x1x8_50e_sthv1_rgb.py)

**Comment by mytk2012** [comment]
But climb's direction is different from run's direction,they should have nothing to do with directions.

**Comment by congee524** [comment]
This is the [sthv1 label csv file](https://box.nju.edu.cn/f/bce31cf0ce61432aab16/?dl=1). index start from 0.
We should not have changed `climb`
