### ISSUE TITLE
Perform Inference after training custom dataset

### ISSUE THREAD

**Issue by wiamadaya** [open-mmlab/mmaction2#826]
I followed the google colab tutorial for training custom dataset (kinetics400_tiny), how should i proceed with inference using the trained model, i am having issue with the config when loading 

`configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py`

```
Use load_from_local loader
The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([2, 2048]) from checkpoint, the shape in current model is torch.Size([400, 2048]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([400]).
```

and i reckon label map has to be modified as well into only two classes `mmaction2/demo/label_map_k400.txt`
eg.
rope_climbing
welding

**Comment by dreamerlin** [comment]
Do you mean you want to use ckpt trained by full K400 to inference on Kinetics400_tiny（which only contains 2 sub class in K400）?

1. Use the full ckpt to finetine on the tiny dataset
2. Keep the full label map to predict, I guess they are the same

**Comment by wiamadaya** [comment]
Actually my final aim is to train a custom dataset with custom class (new class not existed in k400) is it possible? now my understanding we could only able to finetune the model on other datasets with same class/activity to get better performance

**Comment by dreamerlin** [comment]
> Actually my final aim is to train a custom dataset with custom class (new class not existed in k400) is it possible? now my understanding we could only able to finetune the model on other datasets with same class/activity to get better performance

I suggest to use the full ckpt to finetine on the custom dataset @kennymckormick any comments?

**Comment by kennymckormick** [comment]
> Actually my final aim is to train a custom dataset with custom class (new class not existed in k400) is it possible? now my understanding we could only able to finetune the model on other datasets with same class/activity to get better performance

@wiamadaya  Actually, you can finetune the model on any other datasets (We do not require the same taxonomy). The tutorial just provides a very tiny example.  To infer with that trained model (trained on 2 classes), I guess you need to modify the `num_classes` field in the config file and use a new label_map.txt. (I remember that the 2 actions in the tiny dataset are abseiling and blowing glasses)

**Comment by SandyLi2017** [comment]
@kennymckormick sorry i found this issue is helpful for my current issue, do let me know if new issue is needed to be open.
I am also following the colab tutorial for training custom dataset with new classes(which might be sub classes of a class  in k400 like gymactivity1, gymactivity2 and gymactivity3 of gymactivity) and did change the num_classes as 3 and new label_map.txt(list in 3 lines, suppose this be using on inference only?). I also prepared the training/val video dataset  annotation txt file and tried  below on way A and B:
A: class id as 
gymactivity1 0
gymactivity2 1
gymactivity3  2
and pointing to custom dataset followed by model training. After training done to get best top1 acc epoch pth file and use configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py with minor change based on test portion of training config dict as below:
_base_ = ['../../_base_/models/tsn_r50.py']

# dataset settings
dataset_type = 'VideoDataset'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=25,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='TenCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs','label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=2,
    test=dict(
        type=dataset_type,
        ann_file=None,
        data_prefix=None,
        pipeline=test_pipeline))
But still after inference, i am still getting the orig ground truth class id in k400 but not my own custom class to be recognized(which might be my custom dataset volume too small or class id wrongly place in ann file?).
A:  to use class id not in ground truth class id in k400 as 
gymactivity1 400
gymactivity2 401
gymactivity3  402
But this can not be trained to success with below error:
/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     70     except Exception as e:
     71         # Normal TypeError does not print class name.
---> 72         raise type(e)(f'{obj_cls.__name__}: {e}')
     73 
     74 

ValueError: VideoDataset: not enough values to unpack (expected 2, got 0)

Much appreciate if  any guide me thru on the issue.
