### ISSUE TITLE
Newer versions for Windows

### ISSUE THREAD

**Issue by RonSherman** [open-mmlab/mmaction2#828]
I've seen that the latest version for Windows is mmcv_full-1.1.3+torch1.6.0+cu101.
While it's mentioned in the installation guide that Windows is not officially supported, It would help me immensely so I have to ask if are there any plans to release a more updated version for windows in the future?

**Comment by irvingzhang0512** [comment]
Personally, I haven't build mmcv-full on windows. It seems we need to build from source codes, related tutorial [here](https://mmcv.readthedocs.io/en/latest/build.html#build-on-windows)

However, I do have a few tips for using mmaction2 & mmcv(instead of mmcv-full)

+ Should not install mmdet
+ Spatio-temporal models aren't available.
+ Almost all Recognizers(except TIN) are available.

**Comment by innerlee** [comment]
Building mmcv in windows is fine. I happened to tried it yesterday :D

**Comment by innerlee** [comment]
For mmaction2 on windows, recognition demo could run successfully. Haven't tried detection tasks

**Comment by innerlee** [comment]
Created an issue https://github.com/open-mmlab/mmcv/issues/977 in mmcv, since

> the latest version for Windows is mmcv_full-1.1.3+torch1.6.0+cu101

is not exact

**Comment by matrix618** [comment]
windowns be left  :-(
