### ISSUE TITLE
Testing VideoDataset on frames & adding a threshold during testing

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#921]
(1) Do you think that it would make sense to have the option of testing a video dataset on frames as well? Or must one work with a frame dataset for this purpose?
From my understanding, `test.py` does the inference on the clips rather than frame by frame.

I have a situation where the testing accuracy is pretty good, but based on a bunch of `long_video_demo`s, it doesn't feel like I am getting those results (pretty much eyeballing it). I can actually verify this by running `demo.py` on the clips of my testing set. The result will be pretty good and in accordance with the result of `test.py`, but again, on a frame-by-frame basis, not so much.

(2) Also, do you think it would be a good idea to have a threshold for testing so that, if specified, a classification counts as correct (e.g., in the top-k accuracy calculations) only if it also passes the added constraint of being higher than this threshold? This could help in the hyperparameter tuning process.

**Comment by kennymckormick** [comment]
1. Do you think that it would make sense to have the option of testing a video dataset on frames as well?
    
I think it can be a good feature. However, calling it `testing` might not be appropriate. By testing, we mean predicting a single label for a video and validate it with the ground-truth label. However, we don't have ground truth for every single frame. Besides, when testing, you utilize the entire video to get the prediction (thus pretty good). But in `long_video_demo`, you either use a single frame or a short neighboring clip to predict the action label, thus leading to inferior results.

2. Do you think it would be a good idea to have a threshold for testing so that, if specified, a classification counts as correct (e.g., in the top-k accuracy calculations) only if it also passes the added constraint of being higher than this threshold? 

I think it depends on ur need, i.e., make the model predict a large enough score or reduce the predicted score when the model is uncertain. PR welcomed.

**Comment by rlleshi** [comment]
Ok, I will see what I can do :)
