### ISSUE TITLE
Meaning of 'heavy' and 'dense'?

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#968]
There are lots of configs that contain 'heavy' or 'dense'. But what are their meanings? There is also a ```--dense``` argument in ```tools/data/resize_video.py``` (BTW,  its name should be 'resize_video**s**.py' ), is that the same?

**Comment by dreamerlin** [comment]
There is only one config file named with `heavy` due to comparison with the setting of SlowFast, which inflates all conv module. And `dense` in config files means dense sampling pattern for Kinetics. And `--dense` in `tools/data/resize_video.py` means to generate a faster cache for densely resizing videos

**Comment by MakeCent** [comment]
> There is only one config file named with `heavy` due to comparison with the setting of SlowFast, which inflates all conv module. And `dense` in config files means dense sampling pattern for Kinetics. And `--dense` in `tools/data/resize_video.py` means to generate a faster cache for densely resizing videos

Thx
