### ISSUE TITLE
about predict different labels in a video

### ISSUE THREAD

**Issue by JiangWeiHn** [open-mmlab/mmaction2#97]
I have a long video that contains a lot of labels, I want  create a 300 frames detection window .I want to  change the demo.py to do this. But it seems that the demo.py have to read the path of the shortcut  video and got one predict. My temporary treatment plan is when i got 300 frames , I save the video as a temporary file，and  call the demo.py program.then delete  temporary file.  It's stupid and inefficiency  How can i read a long video and get the continuous prediction.please help me.

**Comment by innerlee** [comment]
yeah its a good-to-have feature.

**Comment by kennymckormick** [comment]
You mean to predict a label for each 10 seconds clip, or make the continuous prediction (slide the 300 frames det window with a 10-frame step size, etc.)?

**Comment by innerlee** [comment]
we can output a dense label, each label corresponds to an input frame. the label may be obtained by ensemble nearest three or five predicted frames. and which frame is predicted can be configured by some interval value

**Comment by JiangWeiHn** [comment]
please tell which program could implement this functionality。

**Comment by JiangWeiHn** [comment]
> You mean to predict a label for each 10 seconds clip, or make the continuous prediction (slide the 300 frames det window with a 10-frame step size, etc.)?
 yes ,its what  I mean

**Comment by kennymckormick** [comment]
> we can output a dense label, each label corresponds to an input frame. the label may be obtained by ensemble nearest three or five predicted frames. and which frame is predicted can be configured by some interval value

Yes, actually we can predict the label using just one frame, and 'ensemble 3 or 5 frames' is about smoothing. 
I think for the continuous demo, maybe updating the prediction per 0.1s  or 0.2s is OK?

**Comment by innerlee** [comment]
tsn is about ensemble. so the accuracy would be higher also

**Comment by PoroWang** [comment]
I'm trying to do this as well
Actually my idea is to set a buffer.
For example it can contain 16 frames(buffer size is 16), then these frames can input to any model to output for these 16 frames a prediction.
As time shifting, the buffer will drop the first frame and append the next frame(the 17th frame), then do a prediction, repeatly.
Finally maybe averages 5 or 10 prediction and update the prediction label every x sec(maybe 1sec or something else).
I think it is more smoothing?
I haven't implemented the function because i'm still trying to modify the code.
Could you give me some idea where should i modify? Thank you.

**Comment by dreamerlin** [comment]
We provide a demo to predict different labels in a long video [here](https://github.com/open-mmlab/mmaction2/pull/274).
